### ISSUE TITLE
Vodafone VLans Configuration in DD-WRT

### ISSUE THREAD

**Issue by pauloabmiranda** [Tenza/configurations#1]
Hi,

I have the same problem you had but i have a router with dd-wrt, can you help me or direct me to some tutorial to make the same you did but for dd-wrt.

Thanks in advance,

Paulo Miranda

**Comment by Tenza** [comment]
Hi Paulo,
if you speak Portuguese, this thread might help you:
http://forum.meo.pt/t5/Tutoriais/Tutorial-firmware-10-2-1-L-mais-segundo-router-a-gerir-o-servi%C3%A7o/m-p/51333#U51333

On the described DD-WRT method (3rd), you would have change the vlan 12 to 100, and add the vlans 101 for VOIP and 105 for IPTV, mark all of this as tagged traffic on the same port. After this you should get something on your other router.

Hope it helps.

EDIT: my bad is DD-WRT not Open-WRT, I will get back later. Although, on the same thread, on the 5th method, they say the config for DD-WTR needs to be made with the command line, much like merlin. If so, the commands should be the same, where are you having problems exactly?

**Comment by pauloabmiranda** [comment]
The vodafone router doesn't have bridge mode to pass to everything to my router and i was looking for solutions.
In the mean time i opened an issue with them and they resolved everything making changes to the router of vodafone so it is completely open and passes all the traffic to my router, my router even gets the public ip, it is has if the cable is directly plugin in my router. Their router stays with tv and phone.
Thanks for the help.
